### ISSUE TITLE
SEO of brainfork is forked

### ISSUE THREAD

**Issue by tomgco** [SaraVieira/brainfuck#1]
Description shows "We're sorry but brainfork doesn't work properly without JavaScript enabled. Please enable it to continue. logo."

![We're sorry but brainfork doesn't work properly without JavaScript enabled. Please enable it to continue. logo. ](https://user-images.githubusercontent.com/524382/43956950-f2e51034-9c9d-11e8-9062-f960bac3e44d.png)

**Comment by SaraVieira** [comment]
Amazing description!

I'll fix that today and ALL the SEO 😊

**Comment by tomgco** [comment]
> Amazing description!
> 
> I'll fix that today and ALL the SEO

Great work to both of you on this podcast :clap:

**Comment by SaraVieira** [comment]
Oww! Thank you for listening! Next episode will Monday or Tuesday :)

**Comment by SaraVieira** [comment]
Closed by https://github.com/SaraVieira/brainfuck/commit/f0f3d8918b5061f53bc9e4007226e26d398cc193
